name: Prepare Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-release"

jobs:
  prepare:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        run: |
          RAW_TAG=${GITHUB_REF#refs/tags/}
          VERSION=${RAW_TAG%-release}
          echo "version=$VERSION" >> $GITHUB_ENV
      - name: Update version.txt
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout main
          echo "${version#v}" > libversion/version_self.py
          git add libversion/version_self.py
          git commit -m "Update version_self.py to $version"
          git push origin main
      - name: Create release tag
        env:
          GITHUB_TOKEN: ${{ secrets.REMLA_TOKEN }}
        run: |
          git tag "$version"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} "$version"

